import {
  Team1,
  Team10,
  Team11,
  Team2,
  Team3,
  Team4,
  Team5,
  Team6,
  Team7,
  Team8,
  Team9,
} from "@/assest/team";
import { teamArrType } from "@/types";
export const team2Arr: teamArrType[] = [
  {
    id: 1,
    img: Team4,
    name: "Jhon Deo",
    degignation: "graphics designer",
    phonenumber: 938795472,
    email: "jondeo@gmail.com",
  },
  {
    id: 2,
    img: Team5,
    name: "Jhon Deo",
    degignation: "graphics designer",
    phonenumber: 938795472,
    email: "jondeo@gmail.com",
  },
  {
    id: 3,
    img: Team6,
    name: "Jhon Deo",
    degignation: "graphics designer",
    phonenumber: 938795472,
    email: "jondeo@gmail.com",
  },
  {
    id: 4,
    img: Team7,
    name: "Jhon Deo",
    degignation: "graphics designer",
    phonenumber: 938795472,
    email: "jondeo@gmail.com",
  },
  {
    id: 5,
    img: Team8,
    name: "Jhon Deo",
    degignation: "graphics designer",
    phonenumber: 938795472,
    email: "jondeo@gmail.com",
  },
  {
    id: 6,
    img: Team9,
    name: "Jhon Deo",
    degignation: "graphics designer",
    phonenumber: 938795472,
    email: "jondeo@gmail.com",
  },
  {
    id: 7,
    img: Team10,
    name: "Jhon Deo",
    degignation: "graphics designer",
    phonenumber: 938795472,
    email: "jondeo@gmail.com",
  },
  {
    id: 8,
    img: Team5,
    name: "Jhon Deo",
    degignation: "graphics designer",
    phonenumber: 938795472,
    email: "jondeo@gmail.com",
  },
  {
    id: 9,
    img: Team2,
    name: "Jhon Deo",
    degignation: "graphics designer",
    phonenumber: 938795472,
    email: "jondeo@gmail.com",
  },
  {
    id: 10,
    img: Team11,
    name: "Jhon Deo",
    degignation: "graphics designer",
    phonenumber: 938795472,
    email: "jondeo@gmail.com",
  },
  {
    id: 11,
    img: Team1,
    name: "Jhon Deo",
    degignation: "graphics designer",
    phonenumber: 938795472,
    email: "jondeo@gmail.com",
  },
  {
    id: 12,
    img: Team3,
    name: "Jhon Deo",
    degignation: "graphics designer",
    phonenumber: 938795472,
    email: "jondeo@gmail.com",
  },
];
